services:
  portfolio-web:
    image: nginx:alpine
    container_name: portfolio-website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - portfolio-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: portfolio-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge