version: '3.8'

services:
  portfolio-web:
    image: nginx:alpine
    container_name: portfolio-website
    ports:
      - "80:80"      # Standard HTTP port
      - "443:443"    # HTTPS port for SSL
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - portfolio-network
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: portfolio-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - portfolio-network
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  portfolio-network:
    name: portfolio-network
    driver: bridge

volumes:
  certbot-conf:
  certbot-www:
